// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace AccommodationBooking.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ReservationCreationFeature : object, global::Xunit.IClassFixture<ReservationCreationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Reservation Creation", "    As a Guest\r\n    I want to book accommodation\r\n    So that I can reserve a pla" +
                "ce to stay", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ReservationCreation.feature"
#line hidden
        
        public ReservationCreationFeature(ReservationCreationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ReservationCreation.feature.ndjson", 6);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Successfully create a reservation as a logged-in guest")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Reservation Creation")]
        [global::Xunit.TraitAttribute("Description", "Successfully create a reservation as a logged-in guest")]
        public async global::System.Threading.Tasks.Task SuccessfullyCreateAReservationAsALogged_InGuest()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successfully create a reservation as a logged-in guest", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("I am registered and logged in as \"Guest\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Title",
                            "Description",
                            "Type",
                            "Beds",
                            "MaxGuests",
                            "Amount",
                            "Currency",
                            "Country",
                            "City",
                            "Street",
                            "Building",
                            "Postal",
                            "Photos"});
                table1.AddRow(new string[] {
                            "Mountain Cottage",
                            "Beautiful views",
                            "House",
                            "3",
                            "6",
                            "400",
                            "PLN",
                            "Poland",
                            "Zakopane",
                            "G�rska",
                            "15",
                            "34-500",
                            "https://example.com/cottage.jpg"});
#line 8
    await testRunner.AndAsync("A listing exists with the following data:", ((string)(null)), table1, "And ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "CheckInDaysFromNow",
                            "CheckOutDaysFromNow"});
                table2.AddRow(new string[] {
                            "10",
                            "14"});
#line 11
    await testRunner.WhenAsync("I send a request to create a reservation with the following data:", ((string)(null)), table2, "When ");
#line hidden
#line 14
    await testRunner.ThenAsync("The server response should have status 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
    await testRunner.AndAsync("I should receive the details of the created reservation in the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync("The reservation should be saved in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Check available dates for a listing with no reservations")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Reservation Creation")]
        [global::Xunit.TraitAttribute("Description", "Check available dates for a listing with no reservations")]
        public async global::System.Threading.Tasks.Task CheckAvailableDatesForAListingWithNoReservations()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check available dates for a listing with no reservations", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await testRunner.GivenAsync("I am registered and logged in as \"Guest\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Title",
                            "Description",
                            "Type",
                            "Beds",
                            "MaxGuests",
                            "Amount",
                            "Currency",
                            "Country",
                            "City",
                            "Street",
                            "Building",
                            "Postal",
                            "Photos"});
                table3.AddRow(new string[] {
                            "Beach House",
                            "Ocean view",
                            "House",
                            "2",
                            "4",
                            "500",
                            "PLN",
                            "Poland",
                            "Sopot",
                            "Morska",
                            "20",
                            "81-700",
                            "https://example.com/beach.jpg"});
#line 20
    await testRunner.AndAsync("A listing exists with the following data:", ((string)(null)), table3, "And ");
#line hidden
#line 23
    await testRunner.WhenAsync("I request available dates for the listing starting from 5 days from now for 10 da" +
                        "ys", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
    await testRunner.ThenAsync("The server response should have status 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
    await testRunner.AndAsync("I should receive 11 available dates in the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Check available dates excludes occupied dates")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Reservation Creation")]
        [global::Xunit.TraitAttribute("Description", "Check available dates excludes occupied dates")]
        public async global::System.Threading.Tasks.Task CheckAvailableDatesExcludesOccupiedDates()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check available dates excludes occupied dates", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
    await testRunner.GivenAsync("I am registered and logged in as \"Guest\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Title",
                            "Description",
                            "Type",
                            "Beds",
                            "MaxGuests",
                            "Amount",
                            "Currency",
                            "Country",
                            "City",
                            "Street",
                            "Building",
                            "Postal",
                            "Photos"});
                table4.AddRow(new string[] {
                            "City Apartment",
                            "Downtown",
                            "Apartment",
                            "1",
                            "2",
                            "300",
                            "PLN",
                            "Poland",
                            "Warszawa",
                            "Nowa",
                            "5",
                            "00-100",
                            "https://example.com/city.jpg"});
#line 29
    await testRunner.AndAsync("A listing exists with the following data:", ((string)(null)), table4, "And ");
#line hidden
#line 32
    await testRunner.AndAsync("The listing has an existing reservation from 7 days from now to 10 days from now", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.WhenAsync("I request available dates for the listing starting from 5 days from now for 10 da" +
                        "ys", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.ThenAsync("The server response should have status 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
    await testRunner.AndAsync("The available dates should not include the occupied period", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create reservation after checking available dates")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Reservation Creation")]
        [global::Xunit.TraitAttribute("Description", "Create reservation after checking available dates")]
        public async global::System.Threading.Tasks.Task CreateReservationAfterCheckingAvailableDates()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create reservation after checking available dates", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
    await testRunner.GivenAsync("I am registered and logged in as \"Guest\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Title",
                            "Description",
                            "Type",
                            "Beds",
                            "MaxGuests",
                            "Amount",
                            "Currency",
                            "Country",
                            "City",
                            "Street",
                            "Building",
                            "Postal",
                            "Photos"});
                table5.AddRow(new string[] {
                            "Mountain Cottage",
                            "Beautiful views",
                            "House",
                            "3",
                            "6",
                            "400",
                            "PLN",
                            "Poland",
                            "Zakopane",
                            "G�rska",
                            "15",
                            "34-500",
                            "https://example.com/cottage.jpg"});
#line 39
    await testRunner.AndAsync("A listing exists with the following data:", ((string)(null)), table5, "And ");
#line hidden
#line 42
    await testRunner.AndAsync("The listing has an existing reservation from 5 days from now to 8 days from now", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
    await testRunner.WhenAsync("I request available dates for the listing starting from 3 days from now for 10 da" +
                        "ys", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
    await testRunner.ThenAsync("The server response should have status 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
    await testRunner.AndAsync("The available dates should not include the occupied period", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "CheckInDaysFromNow",
                            "CheckOutDaysFromNow"});
                table6.AddRow(new string[] {
                            "10",
                            "14"});
#line 46
    await testRunner.WhenAsync("I send a request to create a reservation with the following data:", ((string)(null)), table6, "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("The server response should have status 200 OK", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.AndAsync("I should receive the details of the created reservation in the response", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.AndAsync("The reservation should be saved in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ReservationCreationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ReservationCreationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
